### ISSUE TITLE
Not able to read files from HDFS

### ISSUE THREAD

**Issue by GezimSejdiu** [SANSA-Stack/SANSA-DataLake#1]
Hi there,

while adding DataLake (CSV only) example on [SANSA-Notebooks](https://github.com/SANSA-Stack/SANSA-Notebooks) the queries/mapping/config files weren't able to load from Hadoop. This is due to the usage of `Source.fromFile` which uses the local file system (e.g. [The queries are loaded using a file system](https://github.com/SANSA-Stack/SANSA-DataLake/blob/develop/sansa-datalake-spark/src/main/scala/net/sansa_stack/datalake/spark/Mapper.scala#L63)).
Please, consider using `spark.sparkContext.textFile` instead and remove any local file system management (eg. [here](https://github.com/SANSA-Stack/SANSA-DataLake/blob/develop/sansa-datalake-spark/src/main/scala/net/sansa_stack/datalake/spark/Mapper.scala#L135)).

Best regards,

**Comment by mnmami** [comment]
This is done. I've made it that reading from both local and HDFS are possible. We decide based on the file path, whether it has the prefix "hdfs://" or not.
I have used the native Hadoop API instead of Spark's, so to get directly the file string, instead of passing by the RDD.
Other testers are welcome.

**Comment by GezimSejdiu** [comment]
Great! 
Thanks a lot, Mohamed. 
Would it be possible that you create a PR to develop branch so I can start testing the whole pipeline (DataLake -- Query -- Examples -- Notebook) and then we can merge it to the develop branch.

Best regards,

**Comment by GezimSejdiu** [comment]
I just tested it out and the configuration files are able to be read from HDFS. 

I encounter another issue while running the CSV example: `ERROR: invalid Mappings, check syntax.`
Please, see the trace log below for more information.
<details><summary>Stack trace</summary><p>

```
import net.sansa_stack.query.spark.query._
queryFile: String = hdfs://namenode:8020/data/datalake/queries/Q1.sparql
mappingsFile: String = hdfs://namenode:8020/data/datalake/config
configFile: String = hdfs://namenode:8020/data/datalake/mappings.ttl

/*******************************************************************/
/*                         QUERY ANALYSIS                          */
/*******************************************************************/

- The BGP of the input query:  { ?product  <http://www.w3.org/2000/01/rdf-schema#label>  ?label ;
            <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/productPropertyNumeric1>  ?value ;
            a                     <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/Product> ;
            <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/producer>  ?producer .
  ?producer  a                    <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/Producer> ;
            <http://xmlns.com/foaf/spec/homepage>  ?hp .
  ?review   <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/reviewFor>  ?product ;
            a                     <http://schema.org/Review> ;
            <http://purl.org/stuff/rev#reviewer>  ?pers .
  ?pers     <http://xmlns.com/foaf/spec/name>  ?fn ;
            <http://www.europeana.eu/schemas/edm/country>  ?cn .
  ?offer    <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/product>  ?product ;
            a                     <http://schema.org/Offer>
  FILTER ( ?value > 102 )
}

- Number of triple-stars detected: 5
triple: ?product <http://www.w3.org/2000/01/rdf-schema#label> ?label ; <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/productPropertyNumeric1> ?value ; a <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/Product> ; <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/producer> ?producer
triple: ?producer a <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/Producer> ; <http://xmlns.com/foaf/spec/homepage> ?hp
triple: ?review <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/reviewFor> ?product ; a <http://schema.org/Review> ; <http://purl.org/stuff/rev#reviewer> ?pers
triple: ?pers <http://xmlns.com/foaf/spec/name> ?fn ; <http://www.europeana.eu/schemas/edm/country> ?cn
triple: ?offer <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/product> ?product ; a <http://schema.org/Offer> FILTER ( ?value > 102 )
predicateStar: Map(?product -> (?review,<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/reviewFor>), <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/Producer> -> (?producer,a), ?pers -> (?review,<http://purl.org/stuff/rev#reviewer>), <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/Product> -> (?product,a), ?cn -> (?pers,<http://www.europeana.eu/schemas/edm/country>), ?label -> (?product,<http://www.w3.org/2000/01/rdf-schema#label>), ?hp -> (?producer,<http://xmlns.com/foaf/spec/homepage>), <http://schema.org/Review> -> (?review,a), <http://schema.org/Offer> -> (?offer,a), ?producer -> (?product,<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/producer>), ?fn -> (?pers,<http://xmlns.com/foaf/spec/name>), ?value -> (?product,<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/productPropertyNumeric1>))

- Prefixes: Map(http://purl.org/dc/elements/1.1/ -> dc, http://xmlns.com/foaf/spec/ -> foaf, http://www.w3.org/2001/XMLSchema# -> xsd, http://www.w3.org/1999/02/22-rdf-syntax-ns# -> rdf, http://purl.org/dc/terms/ -> dcterms, http://purl.org/goodrelations/v1# -> gr, http://schema.org/ -> schema, http://purl.org/stuff/rev# -> rev, http://www.w3.org/2000/01/rdf-schema# -> rdfs, http://www.europeana.eu/schemas/edm/ -> edm, http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/ -> bsbm)

- Projected vars: [label, value]
............-------........... ?value,(>,102)

- Predicates per star:
star_predicate_var: Map((?review,<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/reviewFor>) -> ?product, (?producer,<http://xmlns.com/foaf/spec/homepage>) -> ?hp, (?pers,<http://xmlns.com/foaf/spec/name>) -> ?fn, (?pers,<http://www.europeana.eu/schemas/edm/country>) -> ?cn, (?offer,<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/product>) -> ?product, (?producer,a) -> <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/Producer>, (?product,<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/producer>) -> ?producer, (?product,<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/productPropertyNumeric1>) -> ?value, (?product,a) -> <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/Product>, (?review,a) -> <http://schema.org/Review>, (?product,<http://www.w3.org/2000/01/rdf-schema#label>) -> ?label, (?review,<http://purl.org/stuff/rev#reviewer>) -> ?pers, (?offer,a) -> <http://schema.org/Offer>)

/*******************************************************************/
/*                  PLAN GENERATION & MAPPINGS                     */
/*******************************************************************/
Stars: ArrayBuffer(?offer, ?pers, ?product, ?producer, ?review)
star_predicate_var: Map((?review,<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/reviewFor>) -> ?product, (?producer,<http://xmlns.com/foaf/spec/homepage>) -> ?hp, (?pers,<http://xmlns.com/foaf/spec/name>) -> ?fn, (?pers,<http://www.europeana.eu/schemas/edm/country>) -> ?cn, (?offer,<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/product>) -> ?product, (?producer,a) -> <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/Producer>, (?product,<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/producer>) -> ?producer, (?product,<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/productPropertyNumeric1>) -> ?value, (?product,a) -> <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/Product>, (?review,a) -> <http://schema.org/Review>, (?product,<http://www.w3.org/2000/01/rdf-schema#label>) -> ?label, (?review,<http://purl.org/stuff/rev#reviewer>) -> ?pers, (?offer,a) -> <http://schema.org/Offer>)
--> Left & right join operands: Set(?product, ?pers, ?review, ?producer, ?offer)
--> Needed predicates all: Set(<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/reviewFor>, <http://www.w3.org/2000/01/rdf-schema#label>, <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/product>, <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/producer>, <http://purl.org/stuff/rev#reviewer>, <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/productPropertyNumeric1>)
---> MAPPING CONSULTATION

- Going to find datasources relevant to ?offer...
...with the (Predicate,Object) pairs: Set((<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/product>,?product), (a,<http://schema.org/Offer>))
...of class: <http://schema.org/Offer>
...for this, the following query will be executed: PREFIX rml: <http://semweb.mmlab.be/ns/rml#>PREFIX rr: <http://www.w3.org/ns/r2rml#>PREFIX foaf: <http://xmlns.com/foaf/spec/>PREFIX nosql: <http://purl.org/db/nosql#>SELECT distinct ?src ?type WHERE {?mp rml:logicalSource ?ls . ?ls rml:source ?src . ?ls nosql:store ?type . ?mp rr:predicateObjectMap ?pom0 . ?pom0 rr:predicate <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/product> . ?pom0 rr:objectMap ?om0 . ?mp rr:subjectMap ?sm . ?sm rr:class <http://schema.org/Offer> . } on hdfs://namenode:8020/data/datalake/config
ERROR: invalid Mappings, check syntax.
result: org.apache.spark.sql.DataFrame = null
java.lang.NullPointerException
  at org.apache.zeppelin.interpreter.BaseZeppelinContext.show(BaseZeppelinContext.java:241)
  at org.apache.zeppelin.interpreter.BaseZeppelinContext.show(BaseZeppelinContext.java:224)
  ... 56 elided
```
</p>
</details>

Could you please have a look what I'm missing from the configurations files ([config](https://github.com/SANSA-Stack/SANSA-Notebooks/blob/develop/examples/data/datalake/config), [mappings](https://github.com/SANSA-Stack/SANSA-Notebooks/blob/develop/examples/data/datalake/mappings.ttl)).

Best regards,

**Comment by mnmami** [comment]
Hello Gezim,
Indeed, the sources there are pointing to the other databases, not to the CSV paths. Could you do similarly to our previous _csv-only_Config_ and _csv-only_Mappings_ found [here](https://github.com/SANSA-Stack/SANSA-Query/tree/develop/sansa-query-spark/src/main/resources)? (PS: on holidays).

**Comment by GezimSejdiu** [comment]
Hi Mohamed, 
I did check them and I'm still getting the same message. 
```sh
- Going to find datasources relevant to ?offer...
...with the (Predicate,Object) pairs: Set((<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/product>,?product), (a,<http://schema.org/Offer>))
...of class: <http://schema.org/Offer>
...for this, the following query will be executed: PREFIX rml: <http://semweb.mmlab.be/ns/rml#>PREFIX rr: <http://www.w3.org/ns/r2rml#>PREFIX foaf: <http://xmlns.com/foaf/spec/>PREFIX nosql: <http://purl.org/db/nosql#>SELECT distinct ?src ?type WHERE {?mp rml:logicalSource ?ls . ?ls rml:source ?src . ?ls nosql:store ?type . ?mp rr:predicateObjectMap ?pom0 . ?pom0 rr:predicate <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/product> . ?pom0 rr:objectMap ?om0 . ?mp rr:subjectMap ?sm . ?sm rr:class <http://schema.org/Offer> . } on hdfs://namenode:8020/data/datalake/config_csv-only
ERROR: invalid Mappings, check syntax.
result: org.apache.spark.sql.DataFrame = null
```
So maybe, the best approach could be that you have a look (after you are back :) ) and see what I'm missing there.

Many thanks in advance.

**Comment by GezimSejdiu** [comment]
Thanks a lot, @mnmami for the help on fixing the issue (the faster bug fix ever ~2seconds, we were mixing the mapping with config path files :( ). 

Just wanted to add another concern here. You already provided the possibility to detect if the path is coming from HDFS or file system (which is great) but maybe consider [my suggestion](https://github.com/SANSA-Stack/SANSA-DataLake/issues/1#issue-393415615) from the beginning of the thread. I'm saying this since users may use different storages (e.g. S3, Alluxio, ... which Spark can read from). We had one use case with Alethio and they used S3 as their storage.

When you find the time, try to resolve this issue as well.

Best regards,

**Comment by mnmami** [comment]
Regarding reading from the other storage formats, it's a valid concern. Will add it to the to-do list. Nevertheless, to keep concern separation, maybe we better move that to a new issue?
